# users API

###
# baseURL
@baseURL = http://localhost:3000

###
# Get specific cart
GET {{baseURL}}/cart/alice

###
# Add item to cart
POST {{baseURL}}/cart/addItem
Content-Type: application/json

{
    "username": "alice",
	"quantity": 1,
    "item_id": "1"
}

###
# Add new item to cart
POST {{baseURL}}/cart/addItem
Content-Type: application/json

{
    "username": "alice",
	"quantity": 1,
    "item_id": "2"
}

###
# Add new item to cart
POST {{baseURL}}/cart/addItem
Content-Type: application/json

{
    "username": "charlie",
	"quantity": 1,
    "item_id": "2"
}

