# users API

###
# baseURL
@baseURL = http://localhost:3000

###
# Find All Items
GET {{baseURL}}/item

###
# List inventory
POST {{baseURL}}/item/listInventory
Content-Type: application/json

{
    "username": "admin"
}

###
# List inventory with ids
POST {{baseURL}}/item/listInventory
Content-Type: application/json

{
    "username": "admin",
    "items": [{"item_id" :"1"},{"item_id" :"2"}]
}

###
# Add item
POST {{baseURL}}/item
Content-Type: application/json

{ 
    "username": "admin2", 
    "item_id": "387",
    "price": 3.20
}

###


###
# Edit User By Id
PUT {{baseURL}}/item
Content-Type: application/json

{
    "username": "admin",
    "item_id": "1",
    "amount": 30
}

###
# Del User By Id
DELETE {{baseURL}}/users/1
